sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.2.3
env:
  - DB=postgres
install:
  - bundle install
env:
  matrix:
    - SOLIDUS_BRANCH=v1.4
    - SOLIDUS_BRANCH=v2.2
script:
  - bundle exec rake test_app
  - ( cd ./spec/dummy && bundle exec rake solidus-adyen:factory_girl:lint RAILS_ENV=test )
  - bundle exec rspec
